name: DBT CI

on:
  # Trigger on pull requests
  pull_request:
    branches: [ "main", "master" ]
  # Enable manual triggers
  workflow_dispatch:
  # Add push trigger for testing
  push:
    branches: [ "main", "master" ]
    paths:
      - '**/*.sql'
      - '**/*.yml'

jobs:
  dbt-test:
    name: dbt CI Checks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery

      - name: Setup GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          default:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: oauth
                project: ${{ secrets.GCP_PROJECT_ID }}
                dataset: zoomcamp_dbt_core_ci
                threads: 4
                timeout_seconds: 300
                location: europe-west2
                priority: interactive
          EOF

      - name: Run dbt deps
        working-directory: ./zoomcamp2025/04-analytics-engineering/taxi_rides_ny
        run: dbt deps

      - name: Run dbt compile
        working-directory: ./zoomcamp2025/04-analytics-engineering/taxi_rides_ny
        run: dbt compile

      - name: Run dbt test
        working-directory: ./zoomcamp2025/04-analytics-engineering/taxi_rides_ny
        run: dbt test 